Updated configure
git-svn-id: https://openmodelica.org/svn/OpenModelica/branches/MathCoreOSMC@3849 f25d12d1-65f4-0310-ae8a-bbce733d8d8e

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1261,6 +1261,7 @@ Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
   --with-CORBA=DIR        use corba installed in DIR /usr/local
+  --with-omniORB=DIR        use omniORB installed in DIR
   --with-MODPAR        Compile with automatic parallelization, requires boost
   --with-BOOST=DIR        With BOOST library in DIR
 
@@ -3759,9 +3760,8 @@ else
   if test -z "$readlineinc" ; then
      { echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6; }
-     { { echo "$as_me:$LINENO: error: Could not find readline header files" >&5
-echo "$as_me: error: Could not find readline header files" >&2;}
-   { (exit 1); exit 1; }; }
+     { echo "$as_me:$LINENO: WARNING: Could not find readline header files" >&5
+echo "$as_me: WARNING: Could not find readline header files" >&2;}
   else
      { echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6; }
@@ -3779,9 +3779,8 @@ else
   if test -z "$readlinelib" ; then
      { echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6; }
-     { { echo "$as_me:$LINENO: error: Could not find readline lib file" >&5
-echo "$as_me: error: Could not find readline lib file" >&2;}
-   { (exit 1); exit 1; }; }
+     { echo "$as_me:$LINENO: WARNING: Could not find readline lib file" >&5
+echo "$as_me: WARNING: Could not find readline lib file" >&2;}
   else
      { echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6; }
@@ -4670,6 +4669,20 @@ else
 
 { echo "$as_me:$LINENO: result: disabling CORBA (no CORBAHOME given)" >&5
 echo "${ECHO_T}disabling CORBA (no CORBAHOME given)" >&6; }; USE_CORBA=""; CORBAHOME="";CORBALIBS="";IDLCMD="";
+
+fi
+
+
+
+# Check whether --with-omniORB was given.
+if test "${with_omniORB+set}" = set; then
+  withval=$with_omniORB;
+    { echo "$as_me:$LINENO: result: enabling omniORB... CORBAHOME=\"$withval\"" >&5
+echo "${ECHO_T}enabling omniORB... CORBAHOME=\"$withval\"" >&6; };
+    USE_CORBA="-DUSE_CORBA -DUSE_OMNIORB";
+    CORBALIBS="-lomniORB4 -lomnithread -lpthread";
+    CORBAHOME="$withval";
+    IDLCMD="omniidl -bcxx -Wbh=.h -Wbs=.cc";
 
 fi
 
